### ISSUE TITLE
fix PDRMIP_spatial_emulator.ipynb example script

### ISSUE THREAD

**Issue by normansteinert** [benmsanderson/METEOR#10]
Need to clean up and fix a few lines in PDRMIP_spatial_emulator.ipynb.

'import library of functions for model':
location of prpatt library has (apparently) changed, so I had to add the lines:

import sys
sys.path.append('src/meteor/')

Also, the functions 'imodel_eof' and 'imodel_filter' are no longer defined in the prpatt library (probably for a good reason). If no longer used, need to clean up the example script.

While at it, it might be a good idea to set up a proper example script of the current functionalities of METEOR for new users.

**Comment by maritsandstad** [comment]
I think this notebook is deprecated and just hanging out because I haven't deleted it yet... Look at the notebooks in the notebooks folder...

**Comment by maritsandstad** [comment]
@normansteinert
